/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: TAIGA-ZOE (https://sketchfab.com/TAIGA-ZOE)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tesla-cybertruck-8950fc178e254c9198b2a8555ef1590a
title: Tesla Cybertruck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube064_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube065_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube066_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube067_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube068_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube069_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube070_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube071_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube072_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube073_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube074_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube075_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube076_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube077_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube078_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube079_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube080_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube081_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube082_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube083_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube084_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube085_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube086_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube087_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube088_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube089_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube090_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube091_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube092_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube093_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube094_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube095_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes['Cube096_Glass?_0'].geometry} material={materials.Glass} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube097_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube098_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube099_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-103.87, -136.16, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube100_Bodyl_0.geometry} material={materials.Bodyl} />
          </group>
          <group position={[-102.58, -35.85, 0]} rotation={[-Math.PI / 2, 0.89, 0]} scale={2.5}>
            <mesh geometry={nodes.Cube027_Tire_0.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Cube027_Tire_0_1.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Cube027_Tire_0_2.geometry} material={materials.Tire} />
          </group>
          <group position={[100.37, -35.85, 0]} rotation={[-Math.PI / 2, -0.89, Math.PI]} scale={2.5}>
            <mesh geometry={nodes.Cube138_Tire_0.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Cube138_Tire_0_1.geometry} material={materials.Tire} />
            <mesh geometry={nodes.Cube138_Tire_0_2.geometry} material={materials.Tire} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Side_glass1_Glass_0.geometry} material={materials.Glass_3} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Side_glass2001_Glass_0.geometry} material={materials.Glass_3} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frant_glass000_Glass_0.geometry} material={materials.Glass_3} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Roof001_Glass_0.geometry} material={materials.Glass_3} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frame_6001_Light_W_0.geometry} material={materials.Light_W} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frame_1002_Light_O_0.geometry} material={materials.Light_O} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frant_glass003_Light_W_0.geometry} material={materials.Light_W} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frame_4001_Light_R_0.geometry} material={materials.Light_R} />
          </group>
          <group position={[163.44, 14.31, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Rear_light002_Light_R_0.geometry} material={materials.Light_R} />
          </group>
          <group position={[163.44, 14.31, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Rear_light001_Glass_0.geometry} material={materials.Glass_3} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frame_3001_Glass_0.geometry} material={materials.Glass_3} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Front_light_Light_W_0.geometry} material={materials.Light_W} />
          </group>
          <group position={[-29.42, -15.62, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={14.44}>
            <mesh geometry={nodes.Cube003_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-29.42, -15.62, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={14.44}>
            <mesh geometry={nodes.Cube004_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-14.65, -17.41, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={14.86}>
            <mesh geometry={nodes.Cube005_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-17.41, -17.41, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={14.86}>
            <mesh geometry={nodes.Cube006_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-29.42, -15.62, 32.22]} rotation={[-Math.PI / 2, 0, 0]} scale={14.44}>
            <mesh geometry={nodes.Cube007_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-29.42, -15.62, 32.22]} rotation={[-Math.PI / 2, 0, 0]} scale={14.44}>
            <mesh geometry={nodes.Cube008_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-14.65, -17.41, 32.22]} rotation={[-Math.PI / 2, 0, 0]} scale={14.86}>
            <mesh geometry={nodes.Cube009_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-17.41, -17.41, 32.22]} rotation={[-Math.PI / 2, 0, 0]} scale={14.86}>
            <mesh geometry={nodes.Cube010_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-29.42, -15.62, -32.12]} rotation={[-Math.PI / 2, 0, 0]} scale={14.44}>
            <mesh geometry={nodes.Cube011_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-29.42, -15.62, -32.12]} rotation={[-Math.PI / 2, 0, 0]} scale={14.44}>
            <mesh geometry={nodes.Cube012_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-14.65, -17.41, -32.12]} rotation={[-Math.PI / 2, 0, 0]} scale={14.86}>
            <mesh geometry={nodes.Cube013_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-17.41, -17.41, -32.12]} rotation={[-Math.PI / 2, 0, 0]} scale={14.86}>
            <mesh geometry={nodes.Cube014_In_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={39.16}>
            <mesh geometry={nodes.Interrior_In_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frant_glass002_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-59.42, 1.26, 0]} rotation={[-Math.PI / 2, -0.27, 0]} scale={9.62}>
            <mesh geometry={nodes.Cube_In_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frant_glass001_Light_B_0.geometry} material={materials.Light_B} />
          </group>
          <group position={[-52.52, 0.94, 31.39]} rotation={[-Math.PI / 2, 0, 0]} scale={5.98}>
            <mesh geometry={nodes.Cube001_In_0.geometry} material={materials.material} />
          </group>
          <group position={[-52.52, 0.94, 31.39]} rotation={[-Math.PI / 2, 0, 0]} scale={5.98}>
            <mesh geometry={nodes.Cube139_In_0.geometry} material={materials.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
